extends Node

var edge_roster = {
	"fan_the_hammer" = {
		"name" = "Fan the Hammer",
		"category" = "Gunslinger",
		"scene" = load("res://scenes/edges/fan_the_hammer.tscn"),
		"sprite" = load("res://sprites/edges/fan_the_hammer.png"),
		"description" = "Attack speed +20%",
	},
	"fleet_of_foot" = {
		"name" = "Fleet of Foot",
		"category" = "Survivalist",
		"scene" = load("res://scenes/edges/fleet_of_foot.tscn"),
		"sprite" = load("res://sprites/edges/fleet_of_foot.png"),
		"description" = "Move speed +20%",
	},
	"spare_bullets" = {
		"name" = "Spare Bullets",
		"category" = "Survivalist",
		"scene" = load("res://scenes/edges/spare_bullets.tscn"),
		"sprite" = load("res://sprites/edges/spare_bullets.png"),
		"description" = "Nearby turrets shoot faster",
	},
	"fungal_aura" = {
		"name" = "Fungal Aura",
		"category" = "Elsewhere",
		"scene" = load("res://scenes/edges/fungal_aura.tscn"),
		"sprite" = load("res://sprites/edges/fungal_aura.png"),
		"description" = "Nearby turrets shoot poison bullets",
	},
	"thick_hide" = {
		"name" = "Thick Hide",
		"category" = "Survivalist",
		"scene" = load("res://scenes/edges/thick_hide.tscn"),
		"sprite" = load("res://sprites/edges/thick_hide.png"),
		"description" = "Furnace armor +1",
	},
	"cursed_appendage" = {
		"name" = "Cursed Appendage",
		"category" = "Elsewhere",
		"scene" = load("res://scenes/edges/cursed_appendage.tscn"),
		"sprite" = load("res://sprites/edges/cursed_appendage.png"),
		"description" = "Assistance from beyond",
	},
	"ricochet" = {
		"name" = "Ricochet",
		"category" = "Survivalist",
		"scene" = load("res://scenes/edges/ricochet.tscn"),
		"sprite" = load("res://sprites/edges/ricochet.png"),
		"description" = "Your bullets bounce",
	},
	"petrichor" = {
		"name" = "Petrichor",
		"category" = "Elsewhere",
		"scene" = load("res://scenes/edges/petrichor.tscn"),
		"sprite" = load("res://sprites/edges/petrichor.png"),
		"description" = "Rain heals the furnace",
	},
	"blood_oil" = {
		"name" = "Blood Oil",
		"category" = "Survivalist",
		"scene" = load("res://scenes/edges/blood_oil.tscn"),
		"sprite" = load("res://sprites/edges/blood_oil.png"),
		"description" = "All poison damage +1",
	},
	"seeing_red" = {
		"name" = "Seeing Red",
		"category" = "Elsewhere",
		"scene" = load("res://scenes/edges/seeing_red.tscn"),
		"sprite" = load("res://sprites/edges/seeing_red.png"),
		"description" = "All fire damage +1",
	},
	"the_voices" = {
		"name" = "The Voices",
		"category" = "Elsewhere",
		"scene" = load("res://scenes/edges/the_voices.tscn"),
		"sprite" = load("res://sprites/edges/the_voices.png"),
		"description" = "Lasso distance up 20%",
	},
	"tomahawk" = {
		"name" = "Tomahawk",
		"category" = "Survival",
		"scene" = load("res://scenes/edges/tomahawk.tscn"),
		"sprite" = load("res://sprites/ui/edge_background.png"),
		"description" = "Melee attack throws an extra hatchet",
	},
	"haggler" = {
		"name" = "Haggler",
		"category" = "Survival",
		"scene" = load("res://scenes/edges/haggler.tscn"),
		"sprite" = load("res://sprites/ui/edge_background.png"),
		"description" = "Selling turrets gains $1.00",
	},
	"elbow_grease" = {
		"name" = "Elbow Grease",
		"category" = "Survival",
		"scene" = load("res://scenes/edges/elbow_grease.tscn"),
		"sprite" = load("res://sprites/ui/edge_background.png"),
		"description" = "New turrets are superpowered for 5 seconds",
	},
	"vitality" = {
		"name" = "Vitality",
		"category" = "Survival",
		"scene" = load("res://scenes/edges/vitality.tscn"),
		"sprite" = load("res://sprites/ui/edge_background.png"),
		"description" = "Furnace max health +10",
	},
	"channeler" = {
		"name" = "Channeler",
		"category" = "Survival",
		"scene" = load("res://scenes/edges/channeler.tscn"),
		"sprite" = load("res://sprites/ui/edge_background.png"),
		"description" = "All shock effects last longer",
	},
}

