extends Node

var enemy_roster = {
	"zombie" = {
		"scene" = load("res://scenes/enemies/enemy_zombie.tscn"),
		"level" = 1.0,
		"type" = "melee",
		"health" = 10,
		"damage" = 5.0,
		"money" = 0.50,
		"speed" = 6000,
		"experience" = 3,
		"max_spawn" = 1,
	},
	"big_zombie" = {
		"scene" = load("res://scenes/enemies/enemy_big_zombie.tscn"),
		"level" = 1.5,
		"type" = "melee",
		"health" = 15,
		"damage" = 8.0,
		"money" = 1.00,
		"speed" = 5500,
		"experience" = 10,
		"max_spawn" = 1,
	},
	"monstrosity" = {
		"scene" = load("res://scenes/enemies/enemy_monstrosity.tscn"),
		"level" = 1.8,
		"health" = 8,
		"type" = "melee",
		"damage" = 10.0,
		"money" = 0.15,
		"speed" = 10000,
		"experience" = 2,
		"max_spawn" = 2,
	},
	"spider" = {
		"scene" = load("res://scenes/enemies/enemy_spider.tscn"),
		"level" = 1.3,
		"health" = 2,
		"type" = "melee",
		"damage" = 2.0,
		"money" = 0.15,
		"speed" = 12000,
		"experience" = 1,
		"max_spawn" = 3,
	},
}
