extends Node

var enemy_roster = {
	"bandit" = {
		"scene" = load("res://scenes/enemies/enemy_bandit.tscn"),
		"level" = 1.3,
		"type" = "ranged",
		"health" = 8,
		"damage" = 2.0,
		"money" = 0.0,
		"speed" = 9000,
		"experience" = 3,
		"max_spawn" = 5,
	},
	"zombie" = {
		"scene" = load("res://scenes/enemies/enemy_zombie.tscn"),
		"level" = 1.0,
		"type" = "melee",
		"health" = 10,
		"damage" = 5.0,
		"money" = 0.40,
		"speed" = 6000,
		"experience" = 3,
		"max_spawn" = 100,
	},
	"big_zombie" = {
		"scene" = load("res://scenes/enemies/enemy_big_zombie.tscn"),
		"level" = 1.5,
		"type" = "melee",
		"health" = 20,
		"damage" = 10.0,
		"money" = 3.0,
		"speed" = 7000,
		"experience" = 10,
		"max_spawn" = 1,
	},
	"monstrosity" = {
		"scene" = load("res://scenes/enemies/enemy_monstrosity.tscn"),
		"level" = 1.8,
		"health" = 8,
		"type" = "melee",
		"damage" = 10.0,
		"money" = 0.50,
		"speed" = 8000,
		"experience" = 2,
		"max_spawn" = 3,
	},
	"spider" = {
		"scene" = load("res://scenes/enemies/enemy_spider.tscn"),
		"level" = 1.3,
		"health" = 2,
		"type" = "melee",
		"damage" = 2.0,
		"money" = 0.15,
		"speed" = 12000,
		"experience" = 1,
		"max_spawn" = 5,
	},
}
