extends Node

var gadget_roster = {
	"pistol_turret" = {
		"name" = "Pistol Turret",
		"last_gadget" = null,
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_pistol_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 7,
		"unlocked" = true,
	},
	"scatter_shot_turret" = {
		"name" = "Scatter Shot Turret",
		"last_gadget" = null,
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_scatter_shot_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 10,
		"unlocked" = false,
	},
	"scatter_shot_turret_more_scatter" = {
		"name" = "More Scatter",
		"last_gadget" = "scatter_shot_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_scatter_shot_turret_more_scatter.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 15,
	},
	"scatter_shot_turret_poison_bullets" = {
		"name" = "Poison Bullets",
		"last_gadget" = "scatter_shot_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_scatter_shot_turret_poison_bullets.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 15,
	},
	"shock_turret" = {
		"name" = "Shock Turret",
		"last_gadget" = null,
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_shock_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 10,
		"unlocked" = false,
	},
	"shock_turret_quick_loading" = {
		"name" = "Quick Loading",
		"last_gadget" = "shock_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_shock_turret_quick_reload.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 10,
	},
	"rifle_turret" = {
		"name" = "Rifle Turret",
		"last_gadget" = "pistol_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_rifle_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_rifle_turret.png"),
		"cost" = 20,
	},
	"rifle_turret_quick_loading" = {
		"name" = "Quick Reload",
		"last_gadget" = "rifle_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_rifle_turret_quick_loading.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_rifle_turret.png"),
		"cost" = 25,
	},
	"rifle_turret_more_damage" = {
		"name" = "More Damage",
		"last_gadget" = "rifle_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_rifle_turret_more_damage.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_rifle_turret.png"),
		"cost" = 25,
	},
	"explosive_turret" = {
		"name" = "Explosive Turret",
		"last_gadget" = null,
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_explosive_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_explosive_turret.png"),
		"cost" = 20,
		"unlocked" = false,
	},
	"explosive_turret_long_range" = {
		"name" = "Longer Range",
		"last_gadget" = "explosive_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_explosive_turret_long_range.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_explosive_turret.png"),
		"cost" = 25,
	},
	"explosive_turret_more_damage" = {
		"name" = "More Damage",
		"last_gadget" = "explosive_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_explosive_turret_more_damage.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_explosive_turret.png"),
		"cost" = 25,
	},
	"flame_turret" = {
		"name" = "Flame Turret",
		"last_gadget" = null,
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_flame_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 10,
		"unlocked" = false,
	},
	"flame_turret_wide_area" = {
		"name" = "Wide Area",
		"last_gadget" = "flame_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_flame_turret_wide_area.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 15,
	},
	"gattling_turret" = {
		"name" = "Gattling Turret",
		"last_gadget" = null,
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_gattling_turret.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 20,
		"unlocked" = false,
	},
	"gattling_turret_more_damage" = {
		"name" = "More Damage",
		"last_gadget" = "gattling_turret",
		"location" = "hard_point",
		"scene" = load("res://scenes/gadgets/gadget_gattling_turret_more_damage.tscn"),
		"sprite" = load("res://sprites/gadgets/gadget_pistol_turret.png"),
		"cost" = 20,
	},
}

#var upgrade_rosters = {
	#default = ["pistol_turret", "flame_turret", "shock_turret", "scatter_shot_turret", "gattling_turret", "explosive_turret"],
	#pistol_turret = ["rifle_turret"],
	#explosive_turret = ["explosive_turret_long_range", "explosive_turret_more_damage"],
	#rifle_turret = ["rifle_turret_quick_loading", "rifle_turret_more_damage"],
	#flame_turret = ["flame_turret_wide_area"],
	#shock_turret = ["shock_turret_quick_loading"],
	#scatter_shot_turret = ["scatter_shot_turret_more_scatter", "scatter_shot_turret_poison_bullets"],
	#gattling_turret = ["gattling_turret_more_damage"],
#}
