extends Node

var towns_roster = {
	"Bog Hollow" = {},
	"Beavercreek" = {},
	"Franchtown" = {},
	"Libbleton" = {},
	"Grobel" = {},
	"Underhill" = {},
	"Tessapeak City" = {},
	"Dagger Pan" = {},
	"Payton's Crossing" = {},
	"Puesta del Sol" = {},
	"Underland" = {},
	"Denton" = {},
	"Indigo Ridge" = {},
	"Stevenson" = {},
	"Long Ranch" = {},
	"Rock Ridge" = {},
	"Hollow Pass" = {},
	"King River" = {},
	"Wren" = {},
	"Grand Lodge" = {},
	"Till's Crown" = {},
	"Dusenberg" = {},
	"Forager's Trail" = {},
	"Drangleic" = {},
	"Avalon Valley" = {},
	"Arrow Hill" = {},
	"Saint-Tropez" = {},
	"Jeatoure Company Town" = {},
	"Shady Tree" = {},
	"Queensport" = {},
}

